name: guatappe
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0-83.0.dev <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_polyline_points: ^1.0.0
  flutter_riverpod: ^2.3.6
  geolocator: ^9.0.2
  go_router: ^7.0.0
  google_maps_flutter: ^2.2.6
  lottie: ^2.3.2
  sliding_up_panel2: ^3.3.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo/
    - assets/images/calle.png
    - assets/images/cordero.png
    - assets/images/malecom.png
    - assets/images/piedra.png
    - assets/images/plazoleta.png
    - assets/icono.png
    - assets/map_style.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 800
